import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>SEOPAGE1</title>
        <meta name="description" content="Generated by Rubiyet" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
    </>
  )
}
